var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
    res.render('index_en', { title: '淺野鍛冶屋' });
});

router.get('/katana', function(req, res, next) {
    res.render('en/katana', { isEn: true, title: '淺野鍛冶屋', contentPath: 'katana', contentName: '刀  katana', descH2: 'Swordsmith Fusataro', descP: 'Founded in Seki city, Gifu pref. in 2004, relocated to Hashima City, Gifu pref. in 2006. In 2012 he was invited to domestic and foreign countries, starting with openstudio of Japanese sword in France, and conducted international exchange with smiths, curators and researchers around the world. Japanese swordsmith with the world\'s oldest technique and highest black smithing technique shown required, and cooperates with the research of steel etc. with the knowledge of  his spirit of exploration.' });
});

router.get('/about', function(req, res, next) {
    res.render('en/about', { isEn: true, title: '淺野鍛冶屋', contentPath: 'about', contentName: '匠  about', descH2: 'ASANO KAJIYA', descP: '501-6236 Gifu prefecture Hashima-city Egira-cho 454-1<br>Phone: 058 374 3818<br><br>"Development of products specializing in Japanese forging technique" "Technical cooperation of the world\'s highest peak smithing technique" "Successor training activity" "Promotion of Japanese sword culture to international society" "Contribution to community"<br><br><table class=aboutTable><tr><td>1997<td>Trained as a disciple under former Fujiwara Kanefusa in the 25th- generation<tr><td>2004<td>Established in Seki city, Gifu Prefecture<tr><td>2005<td>Japanese sword public exercise training in Canada<tr><td>2006<td>moved the training ground to Hashima-city, Gifu Prefecture<tr><td>2012<td>Takaoka Craft Competition Grand Prix<tr><td>2012<td>France (Invitation of the 20th anniversary ceremonial event of the Senshinkan) Japanese sword public demonstration<tr><td>2012<td>France (International sword fighting invitation) Japanese sword public demonstraion<tr><td>2013<td>Solo exhibition "Kanuchi" (Kasaju)<tr><td>2013<td>Canada (sponsored by Tamahagane Art) Instruction of forging technique<tr><td>2013<td>USA (for metal artists) Japanese sword public demonstraion<tr><td>2013<td>USA (invited from Minnesota University) Japanese sword lecture<tr><td>2014<td>France (World Heritage Citadel de Besançon invited) Japanese sword public demonstration<tr><td>2015<td> Started sales of knives and smithing tools at Tokyu Hands Nagoya Takashimaya store in<tr><td>2015<td>Canada (sponsored by Tamahagane Art) Instruction for forging technique<tr><td>2015<td>Shiga Prefecture (Invitation to the Tontenkan Festival Kinjiya Town) Japanese sword public demonstration<tr><td>2015<td>Started accepting forging knife making experience at the workshop<tr><td>2016<td>United States (international exchange Hashima City from Oregon) public training / blacksmith experience<tr><td>2016<td>Canada (invited NAIT University) Japanese sword public training / lecture Canada (sponsored by Tamahagane Art) guidance for forging technique in 2016<tr><td>2016<td>Hashima-city (Namazu Festival) Regional Contribution Project (free forge experience)<tr><td>2017<td>Establishment of workplace and workshop<tr><td>2017<td>Established the Japan-US joint development research institute (USA: Seattle)<tr><td>2018<td> Sword training project "YUGO" (Switzerland: Museum ESPACE HORLOGER)</table>' });
});

router.get('/kitchen_knife', function(req, res, next) {
    res.render('en/kitchen_knife', { isEn: true, title: '淺野鍛冶屋', contentPath: 'kitchen_knife', contentName: '侍  kitchen knife', descH2: 'Traditional technology for familiar kitchen', descP: 'Samurai knife is a traditional Japanese sword technique, carefully forged by hand using pine charcoal, adjusted to the hands, finished with Asanokajiiya original hilt attached. And in the spring of 2017, we added a forge to specialize in knife making.<br><br><a class="more-kitchen" target="_blank" href="https://www.samuraiknife-japan.com/">［Asano\'s knife］https://www.samuraiknife-japan.com/</a>' });
});

router.get('/workshop', function(req, res, next) {
    res.render('en/workshop', { isEn: true, title: '淺野鍛冶屋', contentPath: 'workshop', contentName: '伝  workshop', descH2: 'Learning from the swordsmith, traditional techniques', descP: 'You can challenge the work such as stretching with a hammer, adjusting with a file, blading, quenching and sharpening. A moving experience is waiting for metal to be reborn as a knife. Forging a knife requires a lot of process and time, but it will be completed in just one day (about 7 hours). Swordsmith will teach for beginner in an easy-to-understand manner. Let\'s surround the table with lunch. Please ask anything such as the work of a sword and knife making tips. It is a samurai knife making experience to learn and enjoying.<br><br>Price: ¥ 31,500 / person ~ (for 4 people) Delicious lunch plan<br>Duration: approximately 7 hours<br>Reservation: <a href="https://www.govoyagin.com/ja/activities/japan-gifu-make-your-own-samurai-knife-with-a-certified-swordsmith/3146">Voyagin</a><br><br>Participating in making knives from the United States, Britain, Australia, etc., in particular, we are providing technologies related to swords, So you can experience "Japanese forged knife" in traditional Japanese craftsmanship at the workshop.' });
});
module.exports = router;